Initial version of OpenBSD docs
3mdeb/fwupd-bsd-documentation pull request #2
Opened 2022-08-21 22:20 UTC by SergiiDmytruk

Overview, VM automation, kernel customization and debugging.

2022-09-14 11:59 UTC, TomaszAIR requested changes
@SergiiDmytruk I leave some review, could you please address it?

2022-09-14 11:59 UTC, tomzy-0 commented on openbsd/README.md
> +## Running OpenBSD in QEMU manually
@SergiiDmytruk it would be nice to add here info how to get `OVMF.fd`

2022-09-14 11:59 UTC, tomzy-0 commented on openbsd/README.md
> +                   -smp 6 \
I would add `-smp $(nproc)` to not overstate the host capability

2022-09-14 11:59 UTC, tomzy-0 commented on openbsd/README.md
> +                   -smp 6 \
Like above

2022-09-14 11:59 UTC, tomzy-0 commented on openbsd/README.md
> +Now can reboot and run `> bios bsd.custom` command in bootloader to load newly
This is not working for me. Should not we run `set image bsd.custom` then `boot` in bootloader?

2022-09-14 11:59 UTC, TomaszAIR commented on openbsd/vm/README.md
> +`user` has no password, but it will have your `~/.ssh/id_rsa.pub` listed in
Should console login (not via SSH) should be accessible for that user? I tried but get password prompt so was not able to.

2022-09-14 11:59 UTC, TomaszAIR commented on openbsd/vm/run.sh
> +                   -smp 6 \
Maybe we could set here $(nproc)?

2022-09-14 11:59 UTC, TomaszAIR commented on openbsd/vm/setup.sh
> +                       -smp 6 \
Maybe we could set here $(nproc)?

2022-09-14 16:24 UTC, SergiiDmytruk commented on openbsd/README.md
> +Now can reboot and run `> bios bsd.custom` command in bootloader to load newly
`bsd.custom` should work as well, at least as a first command.

2022-09-14 16:25 UTC, SergiiDmytruk commented on openbsd/vm/README.md
> +`user` has no password, but it will have your `~/.ssh/id_rsa.pub` listed in
No, as there is no password. Can log in as root and do `su user`.

2022-09-16 06:07 UTC, TomaszAIR commented on openbsd/README.md
> +Now can reboot and run `> bios bsd.custom` command in bootloader to load newly
`> bios` at the beginning mislead me, just `bsd.custom` works fine

2022-09-16 11:54 UTC, TomaszAIR approved these changes

2022-09-16 11:54 UTC, merged